[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/404"
  to = "src/app/main/not-found/not-found.component.html"
  status = 404

  [[redirects]]
  from = "/frameui"
  to = "src/app/pages/frame/frame-content/frame-content.component.html"
  status = 200

  [[redirects]]
  from = "/innerframe"
  to = "src/app/pages/frame/innerframe/innerframe.component.html"
  status = 200

