import { CommonModule } from '@angular/common';
import { Component, CUSTOM_ELEMENTS_SCHEMA, inject } from '@angular/core';
import { MatSortModule } from '@angular/material/sort';
import { MatTableModule } from '@angular/material/table';
import { LearningPointComponent } from '../learning-point/learning-point.component';
import { PageheaderComponent } from '../pageheader/pageheader.component';
import { DataTablesModule } from 'angular-datatables';
import { ActivatedRoute } from '@angular/router';
import { UpdateMetaTag } from '../../service/updateMeta';

@Component({
  selector: 'app-advtable',
  imports: [
    CommonModule,
    PageheaderComponent,
    LearningPointComponent,
    MatSortModule,
    MatTableModule,
    DataTablesModule,
  ],
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  templateUrl: './advtable.component.html',
})
export class AdvtableComponent {
  lp = ['WebTable concept', 'Pagination', 'Sorting'];
  link = 'advancetable';
  public universities = [
    {
      name: 'University of Aberdeen',
      'state-province': null,
      alpha_two_code: 'GB',
      country: 'United Kingdom',
      web_pages: ['https://www.abdn.ac.uk/'],
      domains: ['abdn.ac.uk', 'aberdeen.ac.uk'],
    },
    {
      name: 'University of Wales, Aberystwyth',
      'state-province': null,
      alpha_two_code: 'GB',
      country: 'United Kingdom',
      web_pages: ['https://www.aber.ac.uk/'],
      domains: ['aber.ac.uk'],
    },
    {
      name: 'University of Abertay Dundee',
      'state-province': null,
      alpha_two_code: 'GB',
      country: 'United Kingdom',
      web_pages: ['https://www.abertay.ac.uk/'],
      domains: ['abertay.ac.uk'],
    },
    {
      name: 'American InterContinental University - London',
      'state-province': null,
      alpha_two_code: 'GB',
      country: 'United Kingdom',
      web_pages: ['https://www.aiuniv.edu/'],
      domains: ['aiuniv.edu'],
    },
    {
      name: 'Aga Khan University',
      'state-province': null,
      alpha_two_code: 'GB',
      country: 'United Kingdom',
      web_pages: ['https://www.aku.edu/'],
      domains: ['aku.edu'],
    },
    {
      name: 'Anglia Ruskin University',
      'state-province': null,
      alpha_two_code: 'GB',
      country: 'United Kingdom',
      web_pages: ['https://www.anglia.ac.uk/'],
      domains: ['anglia.ac.uk'],
    },
    {
      name: 'Aston University',
      'state-province': null,
      alpha_two_code: 'GB',
      country: 'United Kingdom',
      web_pages: ['https://www.aston.ac.uk/'],
      domains: ['aston.ac.uk'],
    },
    {
      name: 'The American University in London',
      'state-province': null,
      alpha_two_code: 'GB',
      country: 'United Kingdom',
      web_pages: ['https://www.aul.edu/'],
      domains: ['aul.edu'],
    },
    {
      name: 'Heythrop College, University of London',
      'state-province': null,
      alpha_two_code: 'GB',
      country: 'United Kingdom',
      web_pages: ['https://www.heythrop.ac.uk/'],
      domains: ['heythrop.ac.uk'],
    },

    {
      name: 'University of Manchester',
      'state-province': null,
      alpha_two_code: 'GB',
      country: 'United Kingdom',
      web_pages: ['https://www.manchester.ac.uk/'],
      domains: ['manchester.ac.uk', 'mbs.ac.uk', 'man.ac.uk'],
    },
    {
      name: 'Middlesex University',
      'state-province': null,
      alpha_two_code: 'GB',
      country: 'United Kingdom',
      web_pages: ['https://www.mdx.ac.uk/'],
      domains: ['mdx.ac.uk'],
    },
    {
      name: 'Imperial College School of Medicine',
      'state-province': null,
      alpha_two_code: 'GB',
      country: 'United Kingdom',
      web_pages: ['https://www.med.ic.ac.uk/'],
      domains: ['med.ic.ac.uk'],
    },
    {
      name: 'The Manchester Metropolitan University',
      'state-province': null,
      alpha_two_code: 'GB',
      country: 'United Kingdom',
      web_pages: ['https://www.mmu.ac.uk/'],
      domains: ['mmu.ac.uk'],
    },
    {
      name: 'Napier University',
      'state-province': null,
      alpha_two_code: 'GB',
      country: 'United Kingdom',
      web_pages: ['https://www.napier.ac.uk/'],
      domains: ['napier.ac.uk'],
    },
    {
      name: 'University of Newcastle-upon-Tyne',
      'state-province': null,
      alpha_two_code: 'GB',
      country: 'United Kingdom',
      web_pages: ['https://www.ncl.ac.uk/'],
      domains: ['ncl.ac.uk'],
    },
    {
      name: 'University of Wales, Newport',
      'state-province': null,
      alpha_two_code: 'GB',
      country: 'United Kingdom',
      web_pages: ['https://www.newport.ac.uk/'],
      domains: ['newport.ac.uk'],
    },
    {
      name: 'Newport International University',
      'state-province': null,
      alpha_two_code: 'GB',
      country: 'United Kingdom',
      web_pages: ['https://www.niu.org.uk/'],
      domains: ['niu.org.uk'],
    },
    {
      name: 'University of Northampton',
      'state-province': null,
      alpha_two_code: 'GB',
      country: 'United Kingdom',
      web_pages: ['https://www.northampton.ac.uk/'],
      domains: ['northampton.ac.uk'],
    },
    {
      name: 'University of Nottingham',
      'state-province': null,
      alpha_two_code: 'GB',
      country: 'United Kingdom',
      web_pages: ['https://www.nottingham.ac.uk/'],
      domains: ['nottingham.ac.uk'],
    },
    {
      name: 'Nottingham Trent University',
      'state-province': null,
      alpha_two_code: 'GB',
      country: 'United Kingdom',
      web_pages: ['https://www.ntu.ac.uk/'],
      domains: ['ntu.ac.uk'],
    },
    {
      name: 'Open University',
      'state-province': null,
      alpha_two_code: 'GB',
      country: 'United Kingdom',
      web_pages: ['https://www.open.ac.uk/'],
      domains: ['open.ac.uk'],
    },
    {
      name: 'University of Oxford',
      'state-province': null,
      alpha_two_code: 'GB',
      country: 'United Kingdom',
      web_pages: ['https://www.ox.ac.uk/'],
      domains: ['ox.ac.uk'],
    },
    {
      name: 'University of Paisley',
      'state-province': null,
      alpha_two_code: 'GB',
      country: 'United Kingdom',
      web_pages: ['https://www.paisley.ac.uk/'],
      domains: ['paisley.ac.uk'],
    },
    {
      name: 'University of Plymouth',
      'state-province': null,
      alpha_two_code: 'GB',
      country: 'United Kingdom',
      web_pages: ['https://www.plymouth.ac.uk/'],
      domains: ['plymouth.ac.uk'],
    },
    {
      name: 'University of Portsmouth',
      'state-province': null,
      alpha_two_code: 'GB',
      country: 'United Kingdom',
      web_pages: ['https://www.port.ac.uk/'],
      domains: ['port.ac.uk'],
    },
    {
      name: 'Queen Mary, University of London',
      'state-province': null,
      alpha_two_code: 'GB',
      country: 'United Kingdom',
      web_pages: ['https://www.qmul.ac.uk/'],
      domains: ['qmw.ac.uk', 'qmul.ac.uk'],
    },
    {
      name: "The Queen's University Belfast",
      'state-province': null,
      alpha_two_code: 'GB',
      country: 'United Kingdom',
      web_pages: ['https://www.qub.ac.uk/'],
      domains: ['qub.ac.uk'],
    },
    {
      name: 'Royal Academy of Music, University of London',
      'state-province': null,
      alpha_two_code: 'GB',
      country: 'United Kingdom',
      web_pages: ['https://www.ram.ac.uk/'],
      domains: ['ram.ac.uk'],
    },
    {
      name: 'Royal College of Art',
      'state-province': null,
      alpha_two_code: 'GB',
      country: 'United Kingdom',
      web_pages: ['https://www.rca.ac.uk/'],
      domains: ['rca.ac.uk'],
    },
    {
      name: 'Royal College of Music, University of London',
      'state-province': null,
      alpha_two_code: 'GB',
      country: 'United Kingdom',
      web_pages: ['https://www.rcm.ac.uk/'],
      domains: ['rcm.ac.uk'],
    },
    {
      name: 'University of Reading',
      'state-province': null,
      alpha_two_code: 'GB',
      country: 'United Kingdom',
      web_pages: ['https://www.rdg.ac.uk/'],
      domains: ['rdg.ac.uk'],
    },
    {
      name: 'Royal Free Hospital School of Medicine, University of London',
      'state-province': null,
      alpha_two_code: 'GB',
      country: 'United Kingdom',
      web_pages: ['https://www.rfhsm.ac.uk/'],
      domains: ['rfhsm.ac.uk'],
    },
    {
      name: 'The Robert Gordon University',
      'state-province': null,
      alpha_two_code: 'GB',
      country: 'United Kingdom',
      web_pages: ['https://www.rgu.ac.uk/'],
      domains: ['rgu.ac.uk'],
    },
    {
      name: 'Royal Holloway and Bedford New College',
      'state-province': null,
      alpha_two_code: 'GB',
      country: 'United Kingdom',
      web_pages: ['https://www.rhbnc.ac.uk/'],
      domains: ['rhbnc.ac.uk'],
    },
    {
      name: 'Richmond University - The American International University in London',
      'state-province': null,
      alpha_two_code: 'GB',
      country: 'United Kingdom',
      web_pages: ['https://www.richmond.ac.uk/'],
      domains: ['richmond.ac.uk'],
    },
    {
      name: 'Roehampton University of Surrey',
      'state-province': null,
      alpha_two_code: 'GB',
      country: 'United Kingdom',
      web_pages: ['https://www.roehampton.ac.uk/'],
      domains: ['roehampton.ac.uk'],
    },
    {
      name: 'University of Salford',
      'state-province': null,
      alpha_two_code: 'GB',
      country: 'United Kingdom',
      web_pages: ['https://www.salford.ac.uk/'],
      domains: ['salford.ac.uk'],
    },
    {
      name: 'Institute of Advanced Legal Studies, University of London',
      'state-province': null,
      alpha_two_code: 'GB',
      country: 'United Kingdom',
      web_pages: ['https://www.sas.ac.uk/ials/'],
      domains: ['sas.ac.uk'],
    },
    {
      name: 'Institute of Classical Studies, University of London',
      'state-province': null,
      alpha_two_code: 'GB',
      country: 'United Kingdom',
      web_pages: ['https://www.sas.ac.uk/icls/'],
      domains: ['sas.ac.uk'],
    },
    {
      name: 'Institute of Germanic Studies, University of London',
      'state-province': null,
      alpha_two_code: 'GB',
      country: 'United Kingdom',
      web_pages: ['https://www.sas.ac.uk/igs/'],
      domains: ['sas.ac.uk'],
    },
    {
      name: 'Institute of Latin American Studies, University of London',
      'state-province': null,
      alpha_two_code: 'GB',
      country: 'United Kingdom',
      web_pages: ['https://www.sas.ac.uk/ilas/'],
      domains: ['sas.ac.uk'],
    },
    {
      name: 'Warburg Institute, University of London',
      'state-province': null,
      alpha_two_code: 'GB',
      country: 'United Kingdom',
      web_pages: ['https://www.sas.ac.uk/warburg/'],
      domains: ['sas.ac.uk'],
    },
    {
      name: 'South Bank University',
      'state-province': null,
      alpha_two_code: 'GB',
      country: 'United Kingdom',
      web_pages: ['https://www.sbu.ac.uk/'],
      domains: ['sbu.ac.uk'],
    },
    {
      name: 'Schiller International University, London',
      'state-province': null,
      alpha_two_code: 'GB',
      country: 'United Kingdom',
      web_pages: ['https://www.schillerlondon.ac.uk/'],
      domains: ['schillerlondon.ac.uk'],
    },
    {
      name: 'Stratford College London',
      'state-province': null,
      alpha_two_code: 'GB',
      country: 'United Kingdom',
      web_pages: ['https://www.sclondon.ac/'],
      domains: ['sclondon.ac'],
    },
    {
      name: "Saint George's Hospital Medical School, University of London",
      'state-province': null,
      alpha_two_code: 'GB',
      country: 'United Kingdom',
      web_pages: ['https://www.sghms.ac.uk/'],
      domains: ['sghms.ac.uk'],
    },
    {
      name: 'University of Sheffield',
      'state-province': null,
      alpha_two_code: 'GB',
      country: 'United Kingdom',
      web_pages: ['https://www.shef.ac.uk/'],
      domains: ['shef.ac.uk'],
    },
  ];
  constructor() {}
  private route = inject(ActivatedRoute);
  private seoService = inject(UpdateMetaTag);
  dtOptions: any = {};
  ngOnInit() {
    this.dtOptions = {
      pagingType: 'full_numbers',
      pageLength: 5,
      lengthMenu: [5, 10, 25],
      processing: true,
    };
    this.route.data.subscribe((data) => {
      this.seoService.updateMetaTags(data);
    });
  }
}
